name: quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pester-and-lint:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell 7.x
        uses: actions/setup-powershell@v2
        with:
          powerShellVersion: '7.3.x'

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Invoke-Pester -Path ./Tests -Output Detailed -PassThru

      - name: Install ScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning